version: 2.1

defaults: &defaults
  working_directory: ~/react-native-cli

executors:
  node8:
    <<: *defaults
    docker:
      - image: circleci/node:8
  nodelts:
    <<: *defaults
    docker:
      - image: circleci/node:lts
  noderuby:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4-node

commands:
  install-dependencies:
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-native-cli
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: yarn --frozen-lockfile
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  run-lint:
    steps:
      - attach_workspace:
          at: ~/react-native-cli
      - run: yarn lint
  run-typecheck:
    steps:
      - attach_workspace:
          at: ~/react-native-cli
      - run: yarn flow-check
  run-cocoa-pods-tests:
    steps:
      - attach_workspace:
          at: ~/react-native-cli
      - run: yarn test:ci:cocoapods
  run-unit-tests:
    steps:
      - attach_workspace:
          at: ~/react-native-cli
      - run: yarn test:ci:unit
      - store_artifacts:
          path: coverage
          destination: coverage
  run-e2e-tests:
    steps:
      - attach_workspace:
          at: ~/react-native-cli
      - run: yarn test:ci:e2e

jobs:
  setup:
    executor: node8
    steps:
      - install-dependencies
  lint:
    executor: node8
    steps:
      - run-lint
  typecheck:
    executor: node8
    steps:
      - run-typecheck
  cocoa-pods:
    executor: noderuby
    steps:
      - run-cocoa-pods-tests
  unit-tests:
    executor: node8
    steps:
      - run-unit-tests
  e2e-tests:
    executor: node8
    steps:
      - run-e2e-tests
  lts-tests:
    executor: nodelts
    steps:
      - install-dependencies
      - run-lint
      - run-typecheck
      - run-unit-tests
      # TODO: figure out why e2e tests fail even though not interfering with
      # other tests
      # - run-e2e-tests

workflows:
  build-and-test:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - typecheck:
          requires:
            - setup
      - unit-tests:
          requires:
            - setup
      - e2e-tests:
          requires:
            - setup
      - cocoa-pods:
          requires:
            - setup
      - lts-tests
